language: node_js
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
os:
  - linux
  - osx
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install --global yarn --cache-min 999999999
install:
  - npm install
script:
  - ./scripts/lint.sh
  - ./scripts/build.sh
  - ./scripts/push-precompiled.sh
  - ./scripts/package.sh
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    draft: true
    name: Parity UI v0.1.0
    file:
      - ./dist/parity-ui_0.1.0_amd64.deb
      - ./dist/parity-ui_0.1.0_amd64.snap
      - ./dist/parity-ui-0.1.0-x86_64.AppImage
    skip_cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: ci-package
  - provider: releases
    api_key: $GH_TOKEN
    draft: true
    name: Parity UI v0.1.0
    file:
      - "./dist/Parity UI Setup 0.1.0.exe"
      - "./dist/Parity UI-0.1.0.dmg"
    skip_cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = osx
      branch: ci-package
